# Generated by Django 2.2.5 on 2019-09-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paragraph', models.CharField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Post')),
            ],
        ),
    ]
