# Generated by Django 2.2.5 on 2019-09-23 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20190923_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 23, 1, 49, 51, 357437), verbose_name='Date published'),
        ),
    ]
