# Generated by Django 2.2.5 on 2019-09-23 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20190923_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 23, 1, 51, 20, 345239), verbose_name='Date published'),
        ),
    ]
